//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gourmet_s_Choice
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodImage
    {
        public int FoodID { get; set; }
        public byte[] Image { get; set; }
        public byte[] Thumbnail { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
